{% set name = "mkdocstrings-python" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c92304c402928a05c793203dadee7a1a51b5ae56404fd594d0b2db49a7b3957a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - pdm >2
    - pdm-backend
  run:
    - python >=3.8
    - mkdocstrings >=0.20
    - griffe >=0.33

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mkdocstrings-python/
  doc_url: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
